### ISSUE TITLE
1.6.5 does not work on 1.21.1 

### ISSUE THREAD

**Issue by xDangles** [alexdev03/UnlimitedNametags#16]
Tested 1.6.5 release on 1.21.1 and it doesn't work, although 1.6.4 does. Maybe it's the Universal Schedule.

```
[10:17:44] [Server thread/INFO]: [05.12 10:17:44.374] INFO : Starting minecraft server version 1.21.1
[10:17:44] [Server thread/INFO]: [05.12 10:17:44.376] INFO : Loading properties
[10:17:44] [Server thread/INFO]: This server is running Purpur version 1.21.1-2328-ver/1.21.1@d49ca07 (2024-10-23T23:00:30Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
[10:17:45] [Server thread/INFO]: [spark] This server bundles the spark profiler. For more information please visit https://docs.papermc.io/paper/profiling
[10:17:45] [Server thread/INFO]: Server Ping Player Sample Count: 12
[10:17:45] [Server thread/INFO]: Using 4 threads for Netty based IO
[10:17:45] [Server thread/INFO]: [05.12 10:17:45.835] INFO : Chunk system is using 1 I/O threads, 3 worker threads, and population gen parallelism of 3 threads
[10:17:46] [Server thread/WARN]: [Pufferfish] Will not enable SIMD! These optimizations are only safely supported on Java 17-21.
[10:17:46] [Server thread/INFO]: [05.12 10:17:46.033] INFO : Default game type: SURVIVAL
[10:17:46] [Server thread/INFO]: [05.12 10:17:46.034] INFO : Generating keypair
[10:17:46] [Server thread/INFO]: [05.12 10:17:46.071] INFO : Starting Minecraft server secret:60041
[10:17:46] [Server thread/INFO]: [05.12 10:17:46.104] INFO : Using epoll channel type
[10:17:46] [Server thread/INFO]: [05.12 10:17:46.119] INFO : Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[10:17:46] [Server thread/INFO]: [05.12 10:17:46.119] INFO : Paper: Using OpenSSL 3.x.x (Linux x86_64) cipher from Velocity.
[10:17:46] [Server thread/INFO]: [packetevents] Loading server plugin packetevents v2.6.0
[10:17:48] [Server thread/INFO]: [CloudNet-Bridge] Loading server plugin CloudNet-Bridge v4.0.0-RC12-SNAPSHOT
[10:17:48] [Server thread/INFO]: [UnlimitedNameTags] Loading server plugin UnlimitedNameTags v1.6.5
[10:17:48] [Server thread/WARN]: [05.12 10:17:48.117] WARN : **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[10:17:48] [Server thread/WARN]: [05.12 10:17:48.117] WARN : The server will make no attempt to authenticate usernames. Beware.
[10:17:48] [Server thread/WARN]: [05.12 10:17:48.117] WARN : Whilst this makes it possible to use Velocity, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[10:17:48] [Server thread/WARN]: [05.12 10:17:48.117] WARN : Please see https://docs.papermc.io/velocity/security for further information.
[10:17:48] [Server thread/WARN]: [05.12 10:17:48.117] WARN : To change this, set "online-mode" to "true" in the server.properties file.
[10:17:48] [Server thread/INFO]: [05.12 10:17:48.118] INFO : Preparing level "world"
[10:17:48] [Server thread/INFO]: [05.12 10:17:48.454] INFO : Preparing start region for dimension minecraft:overworld
[10:17:49] [Server thread/INFO]: [05.12 10:17:49.115] INFO : Time elapsed: 661 ms
[10:17:49] [Server thread/INFO]: [05.12 10:17:49.116] INFO : Preparing start region for dimension minecraft:the_nether
[10:17:49] [Server thread/INFO]: [05.12 10:17:49.283] INFO : Time elapsed: 168 ms
[10:17:49] [Server thread/INFO]: [packetevents] Enabling packetevents v2.6.0
[10:17:49] [packetevents-update-check-thread/INFO]: [05.12 10:17:49.291] INFO : [packetevents] Checking for updates, please wait...
[10:17:49] [Server thread/INFO]: [CloudNet-Bridge] Enabling CloudNet-Bridge v4.0.0-RC12-SNAPSHOT
[10:17:49] [Server thread/INFO]: [UnlimitedNameTags] Enabling UnlimitedNameTags v1.6.5
[10:17:49] [Server thread/ERROR]: Error occurred while enabling UnlimitedNameTags v1.6.5 (Is it up to date?)
java.lang.NoClassDefFoundError: com/github/Anon8281/universalScheduler/UniversalScheduler
	at UnlimitedNametags.jar/org.alexdev.unlimitednametags.UnlimitedNameTags.onEnable(UnlimitedNameTags.java:64) ~[UnlimitedNametags.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.github.Anon8281.universalScheduler.UniversalScheduler
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?]
	... 13 more
[10:17:49] [Server thread/INFO]: [UnlimitedNameTags] Disabling UnlimitedNameTags v1.6.5
[10:17:49] [Server thread/ERROR]: Error occurred while disabling UnlimitedNameTags v1.6.5
java.lang.NullPointerException: Cannot invoke "org.alexdev.unlimitednametags.events.TrackerManager.onDisable()" because "this.trackerManager" is null
	at UnlimitedNametags.jar/org.alexdev.unlimitednametags.UnlimitedNameTags.onDisable(UnlimitedNameTags.java:251) ~[UnlimitedNametags.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
[10:17:49] [Server thread/INFO]: [spark] Starting background profiler...
[10:17:49] [Server thread/WARN]: [spark] Unable to initialise the async-profiler engine: this version of spark uses a version of async-profiler which does not support java 23+
[10:17:49] [Server thread/WARN]: [spark] Please see here for more information: https://spark.lucko.me/docs/misc/Using-async-profiler
[10:17:49] [Server thread/INFO]: [05.12 10:17:49.597] INFO : Done preparing level "world" (1.479s)
[10:17:49] [Server thread/INFO]: [05.12 10:17:49.605] INFO : Running delayed init tasks
[10:17:49] [Server thread/INFO]: [05.12 10:17:49.606] INFO : Done (10.042s)! For help, type "help"
[10:17:49] [packetevents-update-check-thread/INFO]: [05.12 10:17:49.753] INFO : [packetevents] You are running the latest release of PacketEvents. Your build: (2.6.0)
[10:17:51] [User Authenticator #0/INFO]: [05.12 10:17:51.818] INFO : UUID of player Mioji is f49a4b78-df16-3bbd-b45b-afa41a4fba8e
[10:17:52] [Server thread/INFO]: [05.12 10:17:52.809] INFO : Mioji joined the game
[10:17:52] [Server thread/INFO]: [05.12 10:17:52.908] INFO : Mioji[secret:48494] logged in with entity id 64 at ([world]8.5, 80.0, -7.5)

```

**Comment by alexdev03** [comment]
![image](https://github.com/user-attachments/assets/23739c05-988f-4c3e-8649-316d283e1cf3)
The plugin works fine in 1.21.1, if you have problems join the discord and with proof of purchase I will be happy to help you
