### ISSUE TITLE
The Plugins Doesn't Work

### ISSUE THREAD

**Issue by MCDOOMYT** [alexdev03/UnlimitedNametags#4]
Logs:

`[14:47:31 INFO]: [UnlimitedNameTags] Enabling UnlimitedNameTags v1.3
[14:47:31 WARN]: Enabled plugin with unregistered ConfiguredPluginClassLoader UnlimitedNameTags v1.3
[14:47:32 WARN]: [UnlimitedNameTags] Async task for UnlimitedNameTags v1.3 generated an exception
java.lang.NullPointerException: Cannot invoke "org.alexdev.unlimitednametags.config.Settings.getNametag(org.bukkit.entity.Player)" because the return value of "org.alexdev.unlimitednametags.config.ConfigManager.getSettings()" is null
        at org.alexdev.unlimitednametags.nametags.NameTagManager.addPlayer(NameTagManager.java:101) ~[UnlimitedNametags.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116) ~[?:?]
        at org.alexdev.unlimitednametags.nametags.NameTagManager.lambda$loadAll$0(NameTagManager.java:44) ~[UnlimitedNametags.jar:?]
        at org.alexdev.unlimitednametags.libraries.universalScheduler.foliaScheduler.FoliaScheduler.lambda$runTaskLaterAsynchronously$13(FoliaScheduler.java:140) ~[UnlimitedNametags.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[purpur-1.20.4.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:47:32 INFO]: [UnlimitedNameTags] PacketEvents found, hooking into it
[14:47:32 INFO]: [UnlimitedNameTags] API registered
[14:47:32 INFO]: [UnlimitedNameTags] UnlimitedNameTags has been enabled!`

**Comment by alexdev03** [comment]
This problem should have been fixed in v1.4 that was released only on [built by bit](https://builtbybit.com/resources/unlimitednametags.46172/).
