### ISSUE TITLE
Compatibility with the original color code §

### ISSUE THREAD

**Issue by Noogear** [alexdev03/UnlimitedNametags#9]
The prefix plugin I use implements the RGB color effect in the form of the original §x§R§R§G§G§B§B, which causes the plugin to be unrecognizable. As far as I know, many title plugins use the original color code for the compatibility of the Spigot API, and compatibility should be made.
```java
[02:21:11] [UnlimitedNameTags-PlaceholderManager: 2/ERROR]: [UnlimitedNameTags] Failed to edit nametag for UROR
java.util.concurrent.CompletionException: net.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information.
	<gradient:#5e4fa2:#f79459:0.5>UROR</gradient> .§x§7§9§8§7§d§dtest§r
	                                                 ^^
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: net.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information.
	<gradient:#5e4fa2:#f79459:0.5>UROR</gradient> .§x§7§9§8§7§d§dtest§r
	                                                 ^^
	at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.parseString(TokenParser.java:170) ~[adventure-text-minimessage-4.17.0.jar:?]
	at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.resolvePreProcessTags(TokenParser.java:112) ~[adventure-text-minimessage-4.17.0.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageParser.parseToTree(MiniMessageParser.java:195) ~[adventure-text-minimessage-4.17.0.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat(MiniMessageParser.java:209) ~[adventure-text-minimessage-4.17.0.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:80) ~[adventure-text-minimessage-4.17.0.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:46) ~[adventure-text-minimessage-4.17.0.jar:?]
	at UnlimitedNametags.jar/org.alexdev.unlimitednametags.config.Formatter.lambda$static$2(Formatter.java:29) ~[UnlimitedNametags.jar:?]
	at UnlimitedNametags.jar/org.alexdev.unlimitednametags.config.Formatter.format(Formatter.java:94) ~[UnlimitedNametags.jar:?]
	at UnlimitedNametags.jar/org.alexdev.unlimitednametags.placeholders.PlaceholderManager.format(PlaceholderManager.java:127) ~[UnlimitedNametags.jar:?]
	at UnlimitedNametags.jar/org.alexdev.unlimitednametags.placeholders.PlaceholderManager.lambda$createComponent$11(PlaceholderManager.java:113) ~[UnlimitedNametags.jar:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:194) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212) ~[?:?]
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:622) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:291) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:631) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:637) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:642) ~[?:?]
	at UnlimitedNametags.jar/org.alexdev.unlimitednametags.placeholders.PlaceholderManager.createComponent(PlaceholderManager.java:115) ~[UnlimitedNametags.jar:?]
	at UnlimitedNametags.jar/org.alexdev.unlimitednametags.placeholders.PlaceholderManager.lambda$applyPlaceholders$4(PlaceholderManager.java:87) ~[UnlimitedNametags.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 5 more
```

**Comment by alexdev03** [comment]
Hi, if you own a license you can get support on discord.
